server:
  port: 8001

eureka:
  instance:                         #Eureka实例
    hostname: localhost #Eureka实例所在的主机名

  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

    register-with-eureka: true #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: true       #表示是否从Eureka Server上获取注册信息，默认为true

spring:
  application:
      name: cold-eureka-server